{
    'name': 'Cambiar cuenta corriente facturas ventas enterprise',
    'version': '15.0.0.0.0',
    'author': 'Ganemo',
    'website': 'https://www.ganemo.co',
    'category': 'All',
    'description': 'The account receivable and payable of the invoices, changes according to the currency and the type of proof of payment.',
    'summary': 'The account receivable and payable of the invoices, changes according to the currency and the type of proof of payment.',
    'depends': ['sale_subscription','automatic_account_change'],
    'installable': True,
    'auto_install': False,
    'license': 'Other proprietary',
    'currency': 'USD',
    'price': 0.00,
    'category': 'Accounting/Accounting',
}
