{
    'name': 'Cambiar cuenta corriente facturas ventas',
    'version': '15.0.0.0.0',
    'author': 'Ganemo',
    'website': 'https://www.ganemo.co',
    'live_test_url': 'https://www.ganemo.co/demo',
    'summary': 'The account receivable and payable of the invoices, changes according to the currency and the type of proof of payment.',
    'depends': ['sale', 'automatic_account_change'],
    'installable': True,
    'auto_install': False,
    'license': 'Other proprietary',
    'currency': 'USD',
    'price': 8.00,
    'category': 'Accounting/Accounting',
}
